### ISSUE TITLE
Lack of hDroidGUI

### ISSUE THREAD

**Issue by mlacecilia** [rjopek/harbour-list#1]
Please add to the GUI section the library in subject:
https://github.com/alkresin/HDroidGUI

**Comment by ghost** [comment]
Thank you,
I've already corrected.

**Comment by mlacecilia** [comment]
Hi, the link is correct but the text is still referencing hdcalcul.
In addition, the link to hdcalcul disapparead.
They are two separate contributions: HDroidGUI is the Android framework and hdcalcul is a sample of HDroidGUI usage.

**Comment by ghost** [comment]
Hi Maurizio,
I gave to graphical user interface.
if there is something wrong, please correct you

**Comment by ghost** [comment]
I think it's good now

**Comment by mlacecilia** [comment]
Hi Rafal, yes. This is it.
