### ISSUE TITLE
Please edit `Harbour Functions Dictionary` link

### ISSUE THREAD

**Issue by Petewg** [rjopek/harbour-list#2]
Hi Rafał,
thank you very much, for the reference!

Just a note,
could you please replace the link:
https://github.com/Petewg/V-harbour-core/wiki>
with this one:
https://github.com/Petewg/harbour-core/wiki

Basically, they both have the same contents but the later is more frequently updated,
(probably in the future I'll remove completely the first wiki leaving there just a redirection link).

\<addendum>
 by the way, since you're engaged with lists take a look at this: https://github.com/sindresorhus/awesome

regards,
Pete

**Comment by ghost** [comment]
Hi Pete,

thank you very much, I did not know about the existence of this sindresorhus / awesome
I am sending a request to attach my list

Rafał

**Comment by Petewg** [comment]
That's fine!
Let's hope Harbour will gain a bit more attention, as it indeed deserves.. ;-)
