### ISSUE TITLE
New Harbour contributions

### ISSUE THREAD

**Issue by ghost** [rjopek/harbour-list#5]
Please, revise and add the recent contributions:

https://github.com/ivanilmarcelino/designer

https://github.com/teamQPM/qpm

https://github.com/oohg

**Comment by Petewg** [comment]
Hi, @jjacenty 
thank you very much for the links!

Just added the link for **<teamQPM/qpm>**
Please note that there do exist already links for **\<oohg>**; see https://github.com/Petewg/harbour-list/search?q=oohg&type=commits but seems that the list needs some kind of reshape to be more easily readable/searchable.
Regarding **\<designer>** see this relevant comment https://github.com/Petewg/harbour-list/issues/4#issuecomment-702583232 (however, any different opinion on the matter is very welcome).

**Comment by ghost** [comment]
Hi Petewg, thank you, good job.

Best regards
Jacenty
