### ISSUE TITLE
hbsvg and template-OOP

### ISSUE THREAD

**Issue by ghost** [rjopek/harbour-list#7]
Hi, 
I am writing to request the inclusion of two projects in the official Harbour projects list. These projects aim to showcase various capabilities of Harbour and could serve as useful references for other developers.

https://github.com/dev-harbour/hbsvg
https://github.com/dev-harbour/template-OOP

Best regards,
--Rafał Jopek

**Comment by Petewg** [comment]
Done! (and can't even imagine why they've been forgotten and for so long, really inexcusable!)
Anyway, as they say: "better late than later..." ;-)
